"""tenant keys ontology

Revision ID: 742aa39332c4
Revises: 78532a4f3d68
Create Date: 2026-09-06 21:30:51.418518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '742aa39332c4'
down_revision: Union[str, Sequence[str], None] = '78532a4f3d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ontology_links', sa.Column('company_id', sa.Integer(), nullable=False, server_default='1', comment='租户键（图谱 60-02）；默认 1=单租户 MVP'))
    op.create_index(op.f('ix_ontology_links_company_id'), 'ontology_links', ['company_id'], unique=False)
    op.add_column('ontology_objects', sa.Column('company_id', sa.Integer(), nullable=False, server_default='1', comment='租户键（图谱 60-02）；默认 1=单租户 MVP'))
    op.create_index(op.f('ix_ontology_objects_company_id'), 'ontology_objects', ['company_id'], unique=False)
    op.add_column('ontology_schema_revisions', sa.Column('company_id', sa.Integer(), nullable=False, server_default='1', comment='租户键（图谱 60-02）；默认 1=单租户 MVP'))
    op.create_index(op.f('ix_ontology_schema_revisions_company_id'), 'ontology_schema_revisions', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ontology_schema_revisions_company_id'), table_name='ontology_schema_revisions')
    op.drop_column('ontology_schema_revisions', 'company_id')
    op.drop_index(op.f('ix_ontology_objects_company_id'), table_name='ontology_objects')
    op.drop_column('ontology_objects', 'company_id')
    op.drop_index(op.f('ix_ontology_links_company_id'), table_name='ontology_links')
    op.drop_column('ontology_links', 'company_id')
    # ### end Alembic commands ###
